In [1]:
import numpy as np
import pandas as pd

In [3]:
array = np.array(np.arange(9).reshape(3,3))

In [4]:
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([array,array],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([array,array],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [24]:
ser = pd.Series(range(3),index=['t','u','v'])
ser

t    0
u    1
v    2
dtype: int64

In [23]:
ser1 = pd.Series([3,4],index=['x','y'])
ser1

x    3
y    4
dtype: int64

In [26]:
data =np.concatenate([ser,ser1],axis=0)
data

array([0, 1, 2, 3, 4], dtype=int64)

In [31]:
#concatenate is numpy fuction  and concat is pandas function

In [34]:
pd.concat([ser,ser1])#as we know series comes from pandas liberary so numpy concatenate won't work heere
#here we have to use the concat function.

t    0
u    1
v    2
x    3
y    4
dtype: int64